### ISSUE TITLE
Crash of maps and server whe crafting astral ring

### ISSUE THREAD

**Issue by Xomerian** [ArcAios26/astraladditions#3]
I have tried to craft the ring on an server and on a singleplayer map. Both plant form this crash and make servers unusable.
i play with this modpack :https://www.mediafire.com/file/tkuz19olnzzryro/mods.zip/file
+ CraftTweaker and AstralAddition.
The error is : 
[16:40:24] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_51]
	at arcaios26.astraladditions.crafting.AstralRingRecipe.getOutput(AstralRingRecipe.java:56) ~[AstralRingRecipe.class:?]
	at hellfirepvp.astralsorcery.common.tile.TileAltar.finishCrafting(TileAltar.java:302) ~[TileAltar.class:?]
	at hellfirepvp.astralsorcery.common.tile.TileAltar.doTryCraft(TileAltar.java:279) ~[TileAltar.class:?]
	at hellfirepvp.astralsorcery.common.tile.TileAltar.func_73660_a(TileAltar.java:146) ~[TileAltar.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1838) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
I don't know if this is an imcompatibility from the other mods or from the mod itself.

**Comment by ArcAios26** [comment]
should be fixed with commit# 01ab799a4fd22140300d7838687b27360d1f3771 
build is uploaded to CurseForge
